[package]
name = "iotagent-rust"
version = "0.1.0"
authors = ["Giovanni Curiel dos Santos <giovannicuriel@gmail.com>"]


[dependencies]
rumqtt = "0.10.1"
serde = "1.0.16"
serde_json = "1.0.4"
serde_derive = "1.0.16"
kafka = "0.7"